# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: eBird
        link: /projects/ebird
      - name: iNaturalist
        link: /projects/inaturalist
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Connect
    submenu:
      - name: Google Group (email list)
        icon: email
        link: https://groups.google.com/g/friendsofbnp
  #    - name: LinkedIn
  #      icon: linkedin-square
  #      link: http://www.linkedin.com/in/alainpham
  #    - name: Twitter
  #      icon: twitter
  #      link: https://twitter.com/koint
    
